# This workflow will do a clean install of node dependencies, build the source code and deploy change to gh-pages branch from the build dist/ directory.

name: CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm ci
      - run: npm run build
      - run: ./deploy.sh dist/
