# This workflow will do a clean install of node dev dependencies, and lint the source code using prettier.

name: Lint

on: [push, pull]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm install --only=dev
      - run: npm run lint:check
